use super::ResearchPhase;

pub(super) const RESEARCH_PHASE_DEFINITIONS: [ResearchPhase; 8] = [
    ResearchPhase {
        id: 1,
        name: "Foundation",
        description: "Initial problem analysis, step-back reasoning, question decomposition, ambiguity resolution, research planning, construct definition, dissertation architecture, and chapter synthesis framework.",
        agent_keys: &[
            "step-back-analyzer",
            "self-ask-decomposer",
            "ambiguity-clarifier",
            "research-planner",
            "construct-definer",
            "dissertation-architect",
        ],
    },
    ResearchPhase {
        id: 2,
        name: "Discovery",
        description: "Comprehensive literature mapping, source classification by credibility tiers, citation extraction, and context tier management.",
        agent_keys: &[
            "literature-mapper",
            "source-tier-classifier",
            "citation-extractor",
            "context-tier-manager",
        ],
    },
    ResearchPhase {
        id: 3,
        name: "Architecture",
        description: "Theoretical framework analysis, contradiction detection, gap identification, and risk assessment.",
        agent_keys: &[
            "theoretical-framework-analyst",
            "contradiction-analyzer",
            "gap-hunter",
            "risk-analyst",
        ],
    },
    ResearchPhase {
        id: 4,
        name: "Synthesis",
        description: "Evidence synthesis, pattern recognition, thematic synthesis, theory building, and opportunity identification.",
        agent_keys: &[
            "evidence-synthesizer",
            "pattern-analyst",
            "thematic-synthesizer",
            "theory-builder",
            "opportunity-identifier",
        ],
    },
    ResearchPhase {
        id: 5,
        name: "Design",
        description: "Research methodology design, hypothesis generation, model architecture, analysis planning, sampling strategy, instrument development, validity assurance, methodology scanning, and methodology writing.",
        agent_keys: &[
            "method-designer",
            "hypothesis-generator",
            "model-architect",
            "analysis-planner",
            "sampling-strategist",
            "instrument-developer",
            "validity-guardian",
            "methodology-scanner",
            "methodology-writer",
        ],
    },
    ResearchPhase {
        id: 6,
        name: "Writing",
        description: "Document creation including introduction, literature review, results, discussion, conclusion, and abstract chapters.",
        agent_keys: &[
            "introduction-writer",
            "literature-review-writer",
            "results-writer",
            "discussion-writer",
            "conclusion-writer",
            "abstract-writer",
        ],
    },
    ResearchPhase {
        id: 7,
        name: "Validation",
        description: "Final quality assurance including systematic review, ethics review, adversarial review, confidence quantification, citation validation, reproducibility checking, APA formatting, citation reconciliation, consistency validation, quality assessment, bias detection, and file length management.",
        agent_keys: &[
            "systematic-reviewer",
            "ethics-reviewer",
            "adversarial-reviewer",
            "confidence-quantifier",
            "citation-validator",
            "reproducibility-checker",
            "apa-citation-specialist",
            "citation-reconciler",
            "consistency-validator",
            "quality-assessor",
            "bias-detector",
            "file-length-manager",
        ],
    },
    ResearchPhase {
        id: 8,
        name: "Final Assembly",
        description: "Compose the validated chapter outputs, citation audit, and structural checks into the final university-standard research paper.",
        agent_keys: &["chapter-synthesizer"],
    },
];
