use std::path::Path;

use archon_core::config::GeneratedWorkflowConfig;
use archon_workflow::{
    GeneratedWorkflowLearningContext, WorkflowResult, WorkflowV2HostCall, WorkflowV2HostMethod,
    WorkflowV2HostOptions, WorkflowV2WriteMode,
};

use super::workflow_live_generated_contract::generated_prd_contract_js;
use super::workflow_live_task_universe::WorkflowV2TaskUniverse;

#[path = "workflow_live_generated_scaffold_ownership.rs"]
mod workflow_live_generated_scaffold_ownership;
#[path = "workflow_live_generated_scaffold_verification.rs"]
mod workflow_live_generated_scaffold_verification;

use workflow_live_generated_scaffold_ownership::apply_ownership_expansion_lifecycle;
use workflow_live_generated_scaffold_verification::apply_verification_remediation_lifecycle;

pub(super) fn decomposed_prd_scaffold(
    task: &str,
    target_repository_root: Option<&str>,
    task_universe: &WorkflowV2TaskUniverse,
    governed_learning_context: &[GeneratedWorkflowLearningContext],
    generated_config: &GeneratedWorkflowConfig,
) -> WorkflowResult<String> {
    let task_json = serde_json::to_string(task)?;
    let target_repository_root_json = serde_json::to_string(&target_repository_root)?;
    let project_artifact_root_json = serde_json::to_string(&project_artifact_root(task_universe))?;
    let universe_json = serde_json::to_string_pretty(task_universe)?;
    let learning_json = serde_json::to_string_pretty(governed_learning_context)?;
    let max_repair_iterations = generated_config.max_repair_iterations.max(1).min(8);
    let max_investigation_iterations = generated_config.max_investigation_iterations.max(1).min(8);

    let mut source = String::new();
    source.push_str("export default async function workflow(w) {\n");
    source.push_str("  const taskText = ");
    source.push_str(&task_json);
    source.push_str(";\n");
    source.push_str("  const targetRepositoryRoot = ");
    source.push_str(&target_repository_root_json);
    source.push_str(";\n");
    source.push_str("  const projectArtifactRoot = ");
    source.push_str(&project_artifact_root_json);
    source.push_str(";\n");
    source.push_str("  const taskUniverse = ");
    source.push_str(&indent_json_for_js(&universe_json));
    source.push_str(";\n");
    source.push_str("  const governedLearningContext = ");
    source.push_str(&indent_json_for_js(&learning_json));
    source.push_str(";\n");
    source.push_str(&format!(
        "  const maxRepairIterations = {max_repair_iterations};\n  const maxInvestigationIterations = {max_investigation_iterations};\n",
    ));
    source.push_str(
        r#"  const canonicalTaskUniverse = new Set((taskUniverse.tasks || []).map((task) => task.canonical_task_id).filter(Boolean));
  const maxDependencyWaves = Math.max(1, canonicalTaskUniverse.size * 3);
  const implementationEvidence = [];
  const verificationEvidence = [];
  const reviewEvidence = [];
  const artifactEvidence = [];
  const repairAttempts = [];
  const finalEvidenceRepairAttempts = [];
  const discoveryItems = [
    {
      id: "prd-task-review",
      task: "Read the PRD, decomposed task files, implementation slice, and context files. Return structured requirements, dependency evidence, task coverage requirements, verification requirements, artifact requirements, and residual risks. Distinguish repository source paths from project artifact/data paths under projectArtifactRoot.",
      paths: taskUniverse.source_roots || []
    },
    {
      id: "repository-implementation-audit",
      task: "Inspect the target repository for existing implementation relevant to taskText. Return concrete files read, existing evidence, missing work, test commands, and safety concerns. Do not modify files.",
      paths: taskUniverse.source_roots || []
    },
    {
      id: "acceptance-evidence-audit",
      task: "Map every canonical task in taskUniverse to acceptance criteria, required artifacts, provider/data constraints, and focused verification commands. Use governedLearningContext only as sanitized prior-run hints with evidence refs; verify every claim against current PRD/code. Artifact paths must be checked relative to projectArtifactRoot when they are project artifacts. Do not mark implementation tasks accepted from read-only evidence.",
      paths: taskUniverse.source_roots || []
    }
  ];
"#,
    );
    source.push_str(generated_prd_contract_js());
    source.push_str(include_str!("workflow_live_generated_scaffold_noop.js"));
    source.push_str(include_str!(
        "workflow_live_generated_scaffold_remediation.js"
    ));
    source.push_str(include_str!("workflow_live_generated_scaffold_body_a.js"));
    source.push_str(include_str!("workflow_live_generated_scaffold_body_b.js"));
    source = apply_verification_remediation_lifecycle(source);
    source = apply_ownership_expansion_lifecycle(source);
    Ok(source)
}

/// The approval-time plan for the deterministic decomposed-PRD scaffold.
///
/// The scaffold is generated by Rust, so Rust declares its stage families
/// directly — one entry per family with the write mode the scaffold uses.
/// Dynamic loop indices are runtime concerns; the approval surface reviews
/// stage families. Pinned against the legacy pseudo-parser's extraction by
/// the comparison test until that parser is deleted.
pub(super) fn decomposed_prd_plan_calls() -> Vec<WorkflowV2HostCall> {
    const WORKTREE: Option<WorkflowV2WriteMode> = Some(WorkflowV2WriteMode::Worktree);
    const PLAN: &[(&str, &str, Option<WorkflowV2WriteMode>)] = &[
        ("initial-readonly-discovery", "parallel", None),
        ("canonical-implementation-inventory", "reduce", None),
        ("inventory-shape-repair", "reduce", None),
        ("task-universe-reconcile", "reduce", None),
        ("dependency-graph-repair", "reduce", None),
        ("target-file-discovery", "reduce", None),
        ("verification-requirements-discovery", "reduce", None),
        ("artifact-requirements-discovery", "reduce", None),
        ("provider-environment-discovery", "reduce", None),
        ("evidence-repair", "reduce", None),
        ("blocked-malformed-inventory", "finalReport", None),
        (
            "blocked-empty-implementation-inventory",
            "finalReport",
            None,
        ),
        ("dependency-graph-repair-deadlock", "reduce", None),
        ("blocked-dependency-deadlock", "finalReport", None),
        ("noop-proof-verification", "parallel", None),
        ("noop-evidence-repair", "reduce", None),
        ("noop-proof-reverification", "parallel", None),
        ("blocked-noop-proof-failed", "finalReport", None),
        ("implementation-wave", "fanout", WORKTREE),
        ("remediation-inventory", "reduce", None),
        ("remediation-empty-inventory-repair", "reduce", None),
        ("blocked-malformed-remediation", "finalReport", None),
        ("remediation-wave", "fanout", WORKTREE),
        ("remediation-outcome-repair", "reduce", None),
        ("ownership-expansion-inventory", "reduce", None),
        ("blocked-remediation-unresolved", "finalReport", None),
        ("verification-plan", "reduce", None),
        ("verification-plan-repair", "reduce", None),
        ("blocked-empty-verification", "finalReport", None),
        ("verification-wave", "parallel", None),
        ("verification-failure-triage", "reduce", None),
        ("verification-remediation-inventory", "reduce", None),
        ("post-remediation-verification-plan", "reduce", None),
        ("post-remediation-verification-plan-repair", "reduce", None),
        ("verification-repair-plan", "reduce", None),
        ("verification-repair-shape-repair", "reduce", None),
        ("blocked-verification-failed", "finalReport", None),
        ("wave-completion-evidence-repair", "reduce", None),
        ("blocked-no-completion", "finalReport", None),
        ("blocked-loop-exhaustion", "finalReport", None),
        ("artifact-inventory", "reduce", None),
        ("save-artifact-inventory", "saveArtifact", None),
        ("adversarial-review", "reduce", None),
        ("review-remediation-inventory", "reduce", None),
        ("review-remediation-inventory-repair", "reduce", None),
        ("blocked-empty-review-remediation", "finalReport", None),
        ("review-remediation-wave", "fanout", WORKTREE),
        ("review-verification-plan", "reduce", None),
        ("blocked-empty-review-verification", "finalReport", None),
        ("review-verification-wave", "parallel", None),
        ("blocked-review-verification-failed", "finalReport", None),
        ("blocked-review-unresolved", "finalReport", None),
        ("blocked-review-not-accepted", "finalReport", None),
        ("final-evidence-reconciliation", "reduce", None),
        ("completion-claim-repair", "reduce", None),
        ("artifact-existence-investigation", "parallel", None),
        ("blocked-final-evidence-reconciliation", "finalReport", None),
        ("require-final-artifacts", "requireArtifact", None),
        ("final-zero-gap-audit", "reduce", None),
        ("final-acceptance-gate", "qualityGate", None),
        ("blocked-final-readiness", "finalReport", None),
        ("final-acceptance-report", "finalReport", None),
    ];
    // Families that appear exactly once in the scaffold keep their literal id;
    // every other family is suffixed at runtime, so the plan records its
    // dynamic id prefix (what the deleted pseudo-parser used to synthesize).
    const STATIC_IDS: &[&str] = &[
        "blocked-malformed-inventory",
        "blocked-empty-implementation-inventory",
        "artifact-inventory",
        "save-artifact-inventory",
        "blocked-review-unresolved",
        "blocked-review-not-accepted",
        "blocked-final-evidence-reconciliation",
        "require-final-artifacts",
        "final-zero-gap-audit",
        "final-acceptance-gate",
        "blocked-final-readiness",
        "final-acceptance-report",
    ];
    PLAN.iter()
        .map(|(id, method, write_mode)| {
            let mut options = WorkflowV2HostOptions::default();
            options.item_kind = match *id {
                "implementation-wave" | "remediation-wave" | "review-remediation-wave" => {
                    Some("implementation".to_string())
                }
                "verification-wave" | "review-verification-wave" => {
                    Some("focused_verification".to_string())
                }
                "noop-proof-verification" | "noop-proof-reverification" => {
                    Some("noop_proof".to_string())
                }
                _ => None,
            };
            options.source = match *id {
                "implementation-wave" => Some("readyImplementationItems".to_string()),
                "remediation-wave" => Some("remediationInventory.items".to_string()),
                "review-remediation-wave" => Some("reviewRemediationInventory.items".to_string()),
                _ => None,
            };
            if !STATIC_IDS.contains(id) {
                options.extra.insert(
                    "dynamic_id_prefix".to_string(),
                    serde_json::Value::String(format!("{id}-")),
                );
            }
            WorkflowV2HostCall {
                id: (*id).to_string(),
                method: WorkflowV2HostMethod::parse(method)
                    .unwrap_or_else(|| panic!("static plan method '{method}' must parse")),
                write_mode: *write_mode,
                options,
            }
        })
        .collect()
}

fn indent_json_for_js(json: &str) -> String {
    json.lines().collect::<Vec<_>>().join("\n  ")
}

fn project_artifact_root(task_universe: &WorkflowV2TaskUniverse) -> Option<String> {
    task_universe
        .source_roots
        .iter()
        .chain(task_universe.tasks.iter().map(|task| &task.source_path))
        .filter_map(|path| project_root_from_path(path))
        .next()
}

fn project_root_from_path(path: &str) -> Option<String> {
    for ancestor in Path::new(path).ancestors() {
        if ancestor.join(".archon").is_dir() {
            return Some(ancestor.display().to_string());
        }
    }
    None
}
