use std::collections::BTreeSet;
use std::path::Path;

fn main() {
    embed_git_hash();
    generate_known_env_vars();
}

fn embed_git_hash() {
    let git_hash = std::process::Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|| "unknown".to_string());

    println!("cargo:rustc-env=ARCHON_GIT_HASH={git_hash}");
    println!("cargo:rerun-if-changed=.git/HEAD");
    println!("cargo:rerun-if-changed=.git/refs/");
}

/// Collect every `ARCHON_*` variable the source actually reads (#189 Phase 7).
///
/// 157 of these are referenced across the workspace and not one is read inside
/// the config module — every one is read where it is used. Nothing therefore
/// knows the effective configuration, and answering "why is it behaving like
/// this" means grepping by hand.
///
/// Generated rather than hand-listed because a hand-maintained list rots: it
/// would drift the moment someone adds a variable, and a list that is wrong is
/// worse than no list, since `archon config dump` would then report a real
/// variable as a typo.
fn generate_known_env_vars() {
    let mut names = BTreeSet::new();
    for root in ["src", "crates"] {
        scan_dir(Path::new(root), &mut names);
        println!("cargo:rerun-if-changed={root}");
    }

    let entries: Vec<String> = names.iter().map(|name| format!("    {name:?},")).collect();
    let generated = format!(
        "/// Every `ARCHON_*` variable this build reads somewhere in its source.\n\
         ///\n\
         /// Generated by `build.rs`; do not edit.\n\
         pub const KNOWN_ARCHON_ENV_VARS: &[&str] = &[\n{}\n];\n",
        entries.join("\n")
    );
    let out = std::path::PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"))
        .join("archon_env_vars.rs");
    std::fs::write(&out, generated).expect("write generated env var list");
}

fn scan_dir(dir: &Path, names: &mut BTreeSet<String>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            // `target` holds build output; `tests` holds names no shipped code
            // path reads.
            if path
                .file_name()
                .is_some_and(|name| name == "target" || name == "tests")
            {
                continue;
            }
            scan_dir(&path, names);
        } else if is_scannable(&path)
            && let Ok(text) = std::fs::read_to_string(&path)
        {
            collect_names(&text, names);
        }
    }
}

/// Whether this file's `ARCHON_*` literals describe what the build reads.
///
/// Test modules are skipped. A name that appears only in a test is not read by
/// any shipped code path, and counting it would make `config dump` call a real
/// typo recognised — including, at first, the deliberately-fake name its own
/// test sets. Skipping them keeps the check answering the question it is for.
fn is_scannable(path: &Path) -> bool {
    if path.extension().is_none_or(|ext| ext != "rs") {
        return false;
    }
    path.file_name()
        .and_then(|name| name.to_str())
        .is_some_and(|name| !name.ends_with("_tests.rs") && name != "tests.rs")
}

/// Pull `ARCHON_...` out of every string literal in the file.
///
/// Deliberately not restricted to `env::var(` call sites: the same name is also
/// reached through `var_os`, through constants like `SESSION_DB_ENV`, and
/// through helpers taking a key parameter. Matching the literal wherever it
/// appears finds all three. The cost is over-inclusion — a name that only ever
/// appears in a doc comment is listed as known — and that direction is the safe
/// one: it can only fail to report a typo, never invent one.
fn collect_names(text: &str, names: &mut BTreeSet<String>) {
    let bytes = text.as_bytes();
    let mut index = 0;
    while let Some(found) = text[index..].find("ARCHON_") {
        let start = index + found;
        let mut end = start + "ARCHON_".len();
        while end < bytes.len()
            && (bytes[end].is_ascii_uppercase()
                || bytes[end].is_ascii_digit()
                || bytes[end] == b'_')
        {
            end += 1;
        }
        // A bare `ARCHON_` with nothing after it is a prefix in a format
        // string, not a variable name.
        if end > start + "ARCHON_".len() {
            names.insert(text[start..end].to_string());
        }
        index = end.max(start + 1);
    }
}
