//! SDK message types for TASK-CLI-305.

use serde::{Deserialize, Serialize};

/// A single item yielded by the [`crate::SdkStream`] returned from [`crate::query`]
/// or [`crate::ArchonSession::send`].
///
/// This enum is `#[non_exhaustive]` — new variants may be added in future releases.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[non_exhaustive]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum SdkMessage {
    /// Text output produced by the assistant.
    AssistantMessage { content: String },

    /// The assistant is invoking a tool.
    ToolUse {
        id: String,
        name: String,
        input: serde_json::Value,
    },

    /// The result of a tool call returned to the assistant.
    ToolResult { id: String, content: String },

    /// Final metadata emitted when the conversation ends.
    ResultMessage(SdkResultMessage),
}

/// Final result metadata yielded as the last stream item.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SdkResultMessage {
    /// Why the assistant stopped generating (e.g. `"end_turn"`, `"max_tokens"`).
    pub stop_reason: String,
    /// Token usage for the completed conversation turn.
    pub usage: SdkUsage,
}

/// Token consumption for a completed conversation turn.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SdkUsage {
    /// Tokens in the input (prompt + context).
    pub input_tokens: u64,
    /// Tokens generated by the assistant.
    pub output_tokens: u64,
}
