//! Slash-command registry and handlers for the Archon CLI.
//!
//! Slash commands are user-typed directives (e.g. `/compact`) that are
//! intercepted *before* being sent to the LLM.  Each command implements
//! [`SlashCommandHandler`] and is registered in a [`SlashCommandRegistry`].

use archon_context::compact::{build_summary_request, compact_messages_default};
use archon_context::messages::{ContextMessage, total_estimated_tokens};

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/// The result of executing a slash command.
#[derive(Debug, Clone)]
pub struct CommandOutput {
    /// Human-readable message shown to the user.
    pub message: String,
    /// If `true`, the conversation messages were mutated and the caller should
    /// use the returned `messages` field.
    pub mutated: bool,
    /// The (possibly compacted) message list.  When `mutated` is `false` this
    /// is simply a clone of the input.
    pub messages: Vec<ContextMessage>,
}

/// Minimum number of messages required before compaction is useful.
const MIN_MESSAGES_FOR_COMPACT: usize = 5;

// ---------------------------------------------------------------------------
// Individual command handlers
// ---------------------------------------------------------------------------

/// Handle the `/compact` slash command.
///
/// * If the conversation has fewer than [`MIN_MESSAGES_FOR_COMPACT`] messages
///   the command is a no-op and returns a friendly notice.
/// * Otherwise it delegates to
///   [`archon_context::compact::compact_messages_default`], passing
///   `summary_text` (which should be generated by the caller/LLM).
pub fn handle_compact(messages: &[ContextMessage], summary_text: &str) -> CommandOutput {
    if messages.len() < MIN_MESSAGES_FOR_COMPACT {
        return CommandOutput {
            message: "Nothing to compact (fewer than 5 messages).".into(),
            mutated: false,
            messages: messages.to_vec(),
        };
    }

    let before_tokens = total_estimated_tokens(messages);
    let compacted = compact_messages_default(messages, summary_text);
    let after_tokens = total_estimated_tokens(&compacted);

    let before_k = before_tokens as f64 / 1000.0;
    let after_k = after_tokens as f64 / 1000.0;

    CommandOutput {
        message: format!("Compacting conversation... {before_k:.1}k -> {after_k:.1}k tokens",),
        mutated: true,
        messages: compacted,
    }
}

/// Build the LLM request messages needed to generate a compaction summary.
///
/// This is a thin wrapper around
/// [`archon_context::compact::build_summary_request`] using the default
/// preserve-recent value.
pub fn build_compact_summary_request(messages: &[ContextMessage]) -> Vec<ContextMessage> {
    build_summary_request(
        messages,
        archon_context::compact::DEFAULT_PRESERVE_RECENT_TURNS,
    )
}

// ---------------------------------------------------------------------------
// Slash-command registry
// ---------------------------------------------------------------------------

/// Known slash commands.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SlashCommand {
    Compact,
    Reload,
}

impl SlashCommand {
    /// Try to parse a raw user input string into a slash command.
    ///
    /// Returns `None` if the input is not a recognised command.
    pub fn parse(input: &str) -> Option<Self> {
        let trimmed = input.trim();
        match trimmed {
            "/compact" => Some(Self::Compact),
            "/reload" => Some(Self::Reload),
            _ => None,
        }
    }

    /// The canonical name (with leading `/`).
    pub fn name(self) -> &'static str {
        match self {
            Self::Compact => "/compact",
            Self::Reload => "/reload",
        }
    }

    /// Short help text.
    pub fn description(self) -> &'static str {
        match self {
            Self::Compact => "Compact the conversation to reduce token usage",
            Self::Reload => "Hot-reload configuration from disk",
        }
    }
}

/// Registry that holds all known slash commands.
#[derive(Debug, Clone)]
pub struct SlashCommandRegistry {
    commands: Vec<SlashCommand>,
}

impl SlashCommandRegistry {
    /// Create a registry with the default set of commands.
    pub fn new() -> Self {
        Self {
            commands: vec![SlashCommand::Compact, SlashCommand::Reload],
        }
    }

    /// All registered commands.
    pub fn commands(&self) -> &[SlashCommand] {
        &self.commands
    }

    /// Look up a command by its `/name`.
    pub fn find(&self, input: &str) -> Option<SlashCommand> {
        SlashCommand::parse(input)
    }

    /// Return help text listing every registered command.
    pub fn help_text(&self) -> String {
        let mut out = String::from("Available commands:\n");
        for cmd in &self.commands {
            out.push_str(&format!("  {:12} — {}\n", cmd.name(), cmd.description()));
        }
        out
    }
}

impl Default for SlashCommandRegistry {
    fn default() -> Self {
        Self::new()
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use archon_context::messages::ContextMessage;

    #[test]
    fn parse_compact_command() {
        assert_eq!(SlashCommand::parse("/compact"), Some(SlashCommand::Compact));
        assert_eq!(
            SlashCommand::parse("  /compact  "),
            Some(SlashCommand::Compact)
        );
        assert_eq!(SlashCommand::parse("/unknown"), None);
        assert_eq!(SlashCommand::parse("hello"), None);
        assert_eq!(SlashCommand::parse(""), None);
    }

    #[test]
    fn registry_contains_compact() {
        let reg = SlashCommandRegistry::new();
        assert!(reg.find("/compact").is_some());
        assert!(reg.find("/nope").is_none());
        assert!(reg.commands().contains(&SlashCommand::Compact));
    }

    #[test]
    fn compact_noop_on_short_conversation() {
        let messages = vec![
            ContextMessage::user("hi"),
            ContextMessage::assistant("hello"),
        ];

        let output = handle_compact(&messages, "summary");
        assert!(!output.mutated);
        assert_eq!(output.messages.len(), 2);
        assert!(output.message.contains("fewer than 5 messages"));
    }

    #[test]
    fn compact_noop_on_exactly_four_messages() {
        let messages: Vec<ContextMessage> = (0..4)
            .map(|i| {
                if i % 2 == 0 {
                    ContextMessage::user(&format!("u{i}"))
                } else {
                    ContextMessage::assistant(&format!("a{i}"))
                }
            })
            .collect();

        let output = handle_compact(&messages, "summary");
        assert!(!output.mutated);
        assert!(output.message.contains("fewer than 5 messages"));
    }

    #[test]
    fn compact_triggers_on_enough_messages() {
        let messages: Vec<ContextMessage> = (0..12)
            .map(|i| {
                if i % 2 == 0 {
                    ContextMessage::user(&format!("user message number {i}"))
                } else {
                    ContextMessage::assistant(&format!("assistant response number {i}"))
                }
            })
            .collect();

        let output = handle_compact(&messages, "Compacted summary of earlier conversation");
        assert!(output.mutated);
        // Should be fewer messages than the original 12
        assert!(output.messages.len() < 12);
        // The display message should contain the token counts
        assert!(output.message.contains("Compacting conversation..."));
        assert!(output.message.contains("->"));
        assert!(output.message.contains("k tokens"));
    }

    #[test]
    fn compact_reduces_token_count() {
        let messages: Vec<ContextMessage> = (0..20)
            .map(|i| {
                if i % 2 == 0 {
                    ContextMessage::user(&format!(
                        "User asks a long question about topic {i} with many words"
                    ))
                } else {
                    ContextMessage::assistant(&format!(
                        "Assistant gives a detailed answer about topic {i} with many words"
                    ))
                }
            })
            .collect();

        let before = total_estimated_tokens(&messages);
        let output = handle_compact(&messages, "Brief summary");
        let after = total_estimated_tokens(&output.messages);

        assert!(output.mutated);
        assert!(
            after < before,
            "compacted tokens ({after}) should be less than original ({before})"
        );
    }

    #[test]
    fn registry_help_text_lists_commands() {
        let reg = SlashCommandRegistry::new();
        let help = reg.help_text();
        assert!(help.contains("/compact"));
        assert!(help.contains("Compact the conversation"));
    }

    #[test]
    fn command_name_and_description() {
        assert_eq!(SlashCommand::Compact.name(), "/compact");
        assert!(!SlashCommand::Compact.description().is_empty());
    }

    #[test]
    fn build_compact_summary_request_returns_messages() {
        let messages: Vec<ContextMessage> = (0..10)
            .map(|i| ContextMessage::user(&format!("msg {i}")))
            .collect();

        let request = build_compact_summary_request(&messages);
        assert!(!request.is_empty());
        // The request should contain old messages but not the most recent ones
        let content = request[0].content.as_str().expect("string content");
        assert!(content.contains("msg 0"));
    }
}
