//! Slash-command handlers for the Archon CLI.
//!
//! Slash commands are user-typed directives (e.g. `/compact`) that are
//! intercepted *before* being sent to the LLM.  Skill-based commands are
//! handled by the `SkillRegistry`; this module provides standalone handlers
//! for built-in commands like `/compact`.

use archon_context::compact::{build_summary_request, compact_messages_default};
use archon_context::messages::{ContextMessage, total_estimated_tokens};

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/// The result of executing a slash command.
#[derive(Debug, Clone)]
pub struct CommandOutput {
    /// Human-readable message shown to the user.
    pub message: String,
    /// If `true`, the conversation messages were mutated and the caller should
    /// use the returned `messages` field.
    pub mutated: bool,
    /// The (possibly compacted) message list.  When `mutated` is `false` this
    /// is simply a clone of the input.
    pub messages: Vec<ContextMessage>,
}

/// Minimum number of messages required before compaction is useful.
const MIN_MESSAGES_FOR_COMPACT: usize = 5;

// ---------------------------------------------------------------------------
// Individual command handlers
// ---------------------------------------------------------------------------

/// Handle the `/compact` slash command.
///
/// * If the conversation has fewer than [`MIN_MESSAGES_FOR_COMPACT`] messages
///   the command is a no-op and returns a friendly notice.
/// * Otherwise it delegates to
///   [`archon_context::compact::compact_messages_default`], passing
///   `summary_text` (which should be generated by the caller/LLM).
pub fn handle_compact(messages: &[ContextMessage], summary_text: &str) -> CommandOutput {
    if messages.len() < MIN_MESSAGES_FOR_COMPACT {
        return CommandOutput {
            message: "Nothing to compact (fewer than 5 messages).".into(),
            mutated: false,
            messages: messages.to_vec(),
        };
    }

    let before_tokens = total_estimated_tokens(messages);
    let compacted = compact_messages_default(messages, summary_text);
    let after_tokens = total_estimated_tokens(&compacted);

    let before_k = before_tokens as f64 / 1000.0;
    let after_k = after_tokens as f64 / 1000.0;

    CommandOutput {
        message: format!("Compacting conversation... {before_k:.1}k -> {after_k:.1}k tokens",),
        mutated: true,
        messages: compacted,
    }
}

/// Build the LLM request messages needed to generate a compaction summary.
///
/// This is a thin wrapper around
/// [`archon_context::compact::build_summary_request`] using the default
/// preserve-recent value.
pub fn build_compact_summary_request(messages: &[ContextMessage]) -> Vec<ContextMessage> {
    build_summary_request(
        messages,
        archon_context::compact::DEFAULT_PRESERVE_RECENT_TURNS,
    )
}


// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use archon_context::messages::ContextMessage;

    #[test]
    fn compact_noop_on_short_conversation() {
        let messages = vec![
            ContextMessage::user("hi"),
            ContextMessage::assistant("hello"),
        ];

        let output = handle_compact(&messages, "summary");
        assert!(!output.mutated);
        assert_eq!(output.messages.len(), 2);
        assert!(output.message.contains("fewer than 5 messages"));
    }

    #[test]
    fn compact_noop_on_exactly_four_messages() {
        let messages: Vec<ContextMessage> = (0..4)
            .map(|i| {
                if i % 2 == 0 {
                    ContextMessage::user(&format!("u{i}"))
                } else {
                    ContextMessage::assistant(&format!("a{i}"))
                }
            })
            .collect();

        let output = handle_compact(&messages, "summary");
        assert!(!output.mutated);
        assert!(output.message.contains("fewer than 5 messages"));
    }

    #[test]
    fn compact_triggers_on_enough_messages() {
        let messages: Vec<ContextMessage> = (0..12)
            .map(|i| {
                if i % 2 == 0 {
                    ContextMessage::user(&format!("user message number {i}"))
                } else {
                    ContextMessage::assistant(&format!("assistant response number {i}"))
                }
            })
            .collect();

        let output = handle_compact(&messages, "Compacted summary of earlier conversation");
        assert!(output.mutated);
        // Should be fewer messages than the original 12
        assert!(output.messages.len() < 12);
        // The display message should contain the token counts
        assert!(output.message.contains("Compacting conversation..."));
        assert!(output.message.contains("->"));
        assert!(output.message.contains("k tokens"));
    }

    #[test]
    fn compact_reduces_token_count() {
        let messages: Vec<ContextMessage> = (0..20)
            .map(|i| {
                if i % 2 == 0 {
                    ContextMessage::user(&format!(
                        "User asks a long question about topic {i} with many words"
                    ))
                } else {
                    ContextMessage::assistant(&format!(
                        "Assistant gives a detailed answer about topic {i} with many words"
                    ))
                }
            })
            .collect();

        let before = total_estimated_tokens(&messages);
        let output = handle_compact(&messages, "Brief summary");
        let after = total_estimated_tokens(&output.messages);

        assert!(output.mutated);
        assert!(
            after < before,
            "compacted tokens ({after}) should be less than original ({before})"
        );
    }

    #[test]
    fn build_compact_summary_request_returns_messages() {
        let messages: Vec<ContextMessage> = (0..10)
            .map(|i| ContextMessage::user(&format!("msg {i}")))
            .collect();

        let request = build_compact_summary_request(&messages);
        assert!(!request.is_empty());
        // The request should contain old messages but not the most recent ones
        let content = request[0].content.as_str().expect("string content");
        assert!(content.contains("msg 0"));
    }
}
