//! P1/P2 golden differential tests: the Rust gauntlet + provenance ports must
//! reproduce the Python reference outputs (generated by scripts/fcdp/*.py) exactly.
//! References live under tests/fixtures/ and are the ground truth.

use archon_draft::gauntlet::{GauntletReport, run_gauntlet};
use archon_draft::judge::{self, Gate};
use archon_draft::provenance;
use archon_draft::{Pack, QuoteBank};
use serde::Deserialize;
use serde_json::json;
use std::path::{Path, PathBuf};

fn fixtures() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

/// The m6 fixtures are gitignored (unpublished dissertation content); tests that need them
/// skip when absent so the committed suite passes without them.
fn m6_present() -> bool {
    fixtures().join("m6/pack.json").exists()
}

fn load_pack_bank(pack_path: &Path) -> (Pack, QuoteBank) {
    let pack: Pack = serde_json::from_str(&std::fs::read_to_string(pack_path).unwrap()).unwrap();
    let bank_path = pack_path.parent().unwrap().join(&pack.p4b_bank_path);
    let bank: QuoteBank =
        serde_json::from_str(&std::fs::read_to_string(&bank_path).unwrap()).unwrap();
    (pack, bank)
}

#[derive(Deserialize)]
struct RefReport {
    defects: Vec<String>,
    advisories: Vec<String>,
    pass: bool,
}

fn assert_gauntlet_matches(dir: &Path, sub: &str, presub: &str, reference: &str) {
    let (pack, bank) = load_pack_bank(&dir.join("pack.json"));
    let draft = std::fs::read_to_string(dir.join(sub)).unwrap();
    let pre = std::fs::read_to_string(dir.join(presub)).unwrap();
    let got = run_gauntlet(&draft, &pack, &bank, Some(&pre));

    let refj: RefReport =
        serde_json::from_str(&std::fs::read_to_string(dir.join(reference)).unwrap()).unwrap();
    let want = GauntletReport {
        defects: refj.defects,
        advisories: refj.advisories,
        pass: refj.pass,
    };
    assert_eq!(got, want, "gauntlet mismatch on {sub}");
}

#[test]
fn gauntlet_m6_clean_drafts_all_pass() {
    if !m6_present() {
        eprintln!("skip: m6 fixtures absent (gitignored dissertation content)");
        return;
    }
    // The five validated M6 drafts must produce empty reports (happy path).
    let dir = fixtures().join("m6");
    for tag in ["", "-r1", "-r2", "-r3", "-r4"] {
        assert_gauntlet_matches(
            &dir,
            &format!("draft{tag}.md"),
            &format!("draft-presub{tag}.md"),
            &format!("ref-gauntlet{tag}.json"),
        );
    }
}

#[test]
fn gauntlet_seeded_defects_all_fire() {
    // Multi-defect fixture: G-B/D2, G-C, G-D (retired stem, gendered-pronoun TRUE
    // positive, back-reference, faculty-of-X), G-D/P8, + straight-quote & word-count
    // advisories.
    let dir = fixtures().join("gauntlet");
    assert_gauntlet_matches(&dir, "seeded-sub.md", "seeded-presub.md", "ref-seeded.json");
}

#[test]
fn gauntlet_pronoun_false_positive_suppressed() {
    // "on his account," (appositive → named theorist) must NOT trip the G-D pronoun
    // lock — the negative-lookahead fix. Rust must match Python (no pronoun defect).
    let dir = fixtures().join("gauntlet");
    assert_gauntlet_matches(
        &dir,
        "pronoun-fp-sub.md",
        "pronoun-fp-presub.md",
        "ref-pronoun-fp.json",
    );
    // belt-and-suspenders: assert the specific defect is absent
    let (pack, bank) = load_pack_bank(&dir.join("pack.json"));
    let draft = std::fs::read_to_string(dir.join("pronoun-fp-sub.md")).unwrap();
    let got = run_gauntlet(&draft, &pack, &bank, None);
    assert!(
        !got.defects.iter().any(|d| d.contains("gendered pronoun")),
        "false-positive pronoun defect leaked: {:?}",
        got.defects
    );
}

#[test]
fn gauntlet_unsubstituted_marker_detected() {
    let dir = fixtures().join("gauntlet");
    assert_gauntlet_matches(
        &dir,
        "marker-left-sub.md",
        "marker-left-presub.md",
        "ref-marker-left.json",
    );
}

#[test]
fn gauntlet_exemplar_leak_detected() {
    // An 8-gram lifted verbatim from a P2b exemplar (not bank-covered) must fire the
    // exemplar-leak defect — the one G-B branch the other fixtures don't exercise.
    let dir = fixtures().join("gauntlet");
    assert_gauntlet_matches(
        &dir,
        "exemplar-leak-sub.md",
        "exemplar-leak-presub.md",
        "ref-exemplar-leak.json",
    );
}

fn assert_judge_extraction_matches(gate: Gate, text_file: &str, reference: &str) {
    let dir = fixtures().join("judge");
    let text = std::fs::read_to_string(dir.join(text_file)).unwrap();
    let (order, defects, transcript) = judge::evaluate(gate, "part-ii-two-unions-v1", &text);
    let got = json!({
        "battery_order": order,
        "defects": defects,
        "transcript": transcript,
    });
    let want: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(dir.join(reference)).unwrap()).unwrap();
    assert_eq!(got, want, "judge extraction mismatch on {text_file}");
}

#[test]
fn judge_ge_extraction_matches_python() {
    // Mixed clean YES/NO (bad_on defects), bold/paren numbering, one missing verdict.
    assert_judge_extraction_matches(Gate::GE, "ge-mixed.txt", "ref-ge-mixed.json");
}

#[test]
fn judge_gg_extraction_matches_python() {
    // Case-insensitive verdict + two fail-closed items.
    assert_judge_extraction_matches(Gate::GG, "gg-failclosed.txt", "ref-gg-failclosed.json");
}

#[test]
fn provenance_verifies_real_m6_chain() {
    if !m6_present() {
        eprintln!("skip: m6 fixtures absent (gitignored dissertation content)");
        return;
    }
    // Direct test of canonical_json fidelity: the Python-written 19-record chain must
    // verify under the Rust recomputation (chain_hash = sha256(prev+content+canonical(detail))).
    let chain = fixtures().join("m6/provenance.jsonl");
    assert!(
        provenance::verify(&chain).unwrap(),
        "M6 chain failed to verify"
    );
}

#[test]
fn provenance_declaration_matches_python() {
    if !m6_present() {
        eprintln!("skip: m6 fixtures absent (gitignored dissertation content)");
        return;
    }
    let dir = fixtures().join("m6");
    let (pack, _bank) = load_pack_bank(&dir.join("pack.json"));
    let recs = provenance::read_chain(&dir.join("provenance.jsonl")).unwrap();
    let got = provenance::declare(&recs, &pack);
    let want = std::fs::read_to_string(dir.join("declaration.md")).unwrap();
    assert_eq!(
        got.trim_end_matches('\n'),
        want.trim_end_matches('\n'),
        "declaration mismatch"
    );
}

#[test]
fn provenance_record_roundtrip() {
    // record → verify on a fresh temp chain (tamper-evident: mutating a link breaks it).
    let dir = std::env::temp_dir().join(format!("fcdp-prov-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    let chain = dir.join("chain.jsonl");
    let _ = std::fs::remove_file(&chain);
    let art = dir.join("artifact.md");
    std::fs::write(&art, "some drafted prose").unwrap();

    provenance::record(
        &chain,
        &art,
        "d2-draft",
        &serde_json::json!({"gates_run": [], "words": 3}),
    )
    .unwrap();
    provenance::record(
        &chain,
        &art,
        "revision",
        &serde_json::json!({"cycle": 1, "gates_run": ["G-A"]}),
    )
    .unwrap();
    assert!(provenance::verify(&chain).unwrap());

    // tamper: rewrite a detail without recomputing → must fail
    let mut recs = provenance::read_chain(&chain).unwrap();
    recs[0].detail = serde_json::json!({"gates_run": [], "words": 999});
    assert!(!provenance::verify_records(&recs));

    let _ = std::fs::remove_dir_all(&dir);
}
