use super::super::agents::GameTheoryTier;

pub static GAMETHEORY_TIERS: &[GameTheoryTier] = &[
    GameTheoryTier {
        id: 1,
        name: "Core Analysts",
        description: "",
        agent_keys: &[
            "extensive-form-modeler",
            "game-classifier",
            "information-structure-mapper",
            "payoff-elicitor",
            "payoff-matrix-builder",
            "strategy-space-enumerator",
        ],
    },
    GameTheoryTier {
        id: 2,
        name: "Equilibrium Finders",
        description: "",
        agent_keys: &[
            "bayesian-equilibrium-analyst",
            "correlated-equilibrium-designer",
            "dominant-strategy-identifier",
            "mixed-strategy-calculator",
            "nash-equilibrium-finder",
            "subgame-perfect-analyzer",
            "trembling-hand-refiner",
        ],
    },
    GameTheoryTier {
        id: 3,
        name: "Cooperative Game Specialists",
        description: "",
        agent_keys: &[
            "banzhaf-power-auditor",
            "coalition-formation-strategist",
            "core-stability-analyst",
            "nucleolus-calculator",
            "shapley-value-calculator",
        ],
    },
    GameTheoryTier {
        id: 4,
        name: "Classic Game Pattern Recognizers",
        description: "",
        agent_keys: &[
            "battle-of-sexes-coordinator",
            "centipede-game-analyst",
            "chicken-brinksmanship-tactician",
            "matching-pennies-randomizer",
            "prisoners-dilemma-detector",
            "public-goods-diagnostician",
            "stag-hunt-analyst",
            "tragedy-commons-analyst",
            "trust-game-analyst",
            "ultimatum-bargainer",
        ],
    },
    GameTheoryTier {
        id: 5,
        name: "Dynamic & Repeated Games",
        description: "",
        agent_keys: &[
            "backward-induction-solver",
            "cooperation-emergence-analyst",
            "folk-theorem-applier",
            "reputation-game-modeler",
            "stochastic-game-analyst",
            "tit-for-tat-strategist",
        ],
    },
    GameTheoryTier {
        id: 6,
        name: "Information & Bayesian Games",
        description: "",
        agent_keys: &[
            "asymmetric-info-detective",
            "bayesian-belief-updater",
            "cheap-talk-evaluator",
            "credibility-assessor",
            "screening-mechanism-designer",
            "signaling-game-analyst",
        ],
    },
    GameTheoryTier {
        id: 7,
        name: "Mechanism Design & Auctions",
        description: "",
        agent_keys: &[
            "auction-strategist",
            "incentive-compatibility-auditor",
            "matching-market-designer",
            "mechanism-designer",
            "revenue-equivalence-analyst",
            "vcg-architect",
        ],
    },
    GameTheoryTier {
        id: 8,
        name: "Behavioral & Evolutionary Games",
        description: "",
        agent_keys: &[
            "behavioral-bias-detector",
            "ess-detector",
            "evolutionary-strategy-analyst",
            "fairness-preferences-analyst",
            "level-k-reasoning-profiler",
            "loss-aversion-analyst",
            "quantal-response-modeler",
        ],
    },
    GameTheoryTier {
        id: 9,
        name: "Strategic Tactics & Conflict",
        description: "",
        agent_keys: &[
            "bluff-and-deception-analyst",
            "brinkmanship-tactician",
            "commitment-device-engineer",
            "coopetition-strategist",
            "deterrence-theorist",
            "first-mover-analyst",
            "focal-point-identifier",
            "negotiation-strategist",
            "threat-credibility-assessor",
            "war-of-attrition-analyst",
        ],
    },
    GameTheoryTier {
        id: 10,
        name: "Applied Game Theory",
        description: "",
        agent_keys: &[
            "business-strategy-gamifier",
            "conflict-resolution-theorist",
            "geopolitical-game-analyst",
            "market-competition-modeler",
            "social-interaction-gamifier",
            "voting-strategy-analyst",
        ],
    },
    GameTheoryTier {
        id: 11,
        name: "Social & Political Games",
        description: "",
        agent_keys: &[
            "cohesion-discipline-devotion-auditor",
            "dialectic-tension-mapper",
            "diaspora-dynamics-analyst",
            "elite-overproduction-diagnostician",
            "father-son-dynastic-analyst",
            "legitimacy-crisis-analyst",
            "myth-making-strategist",
            "poor-conquers-rich-analyst",
            "power-transition-analyst",
            "propaganda-detector",
        ],
    },
    GameTheoryTier {
        id: 12,
        name: "Meta-Game & Synthesis",
        description: "",
        agent_keys: &[
            "common-knowledge-analyst",
            "counterfactual-simulator",
            "equilibrium-selector",
            "game-tree-archaeologist",
            "meta-game-designer",
        ],
    },
];
