//! GNN parity test — Rust forward pass must match TS reference fixtures.
//!
//! Acceptance gate for v0.1.24: cosine_similarity >= 0.999 across all fixtures.
//! Fixtures generated by scripts/generate-gnn-fixtures.cjs and committed to repo.
//! No Node, no ts-node, no network access during `cargo test`.

use archon_pipeline::learning::gnn::cache::CacheConfig;
use archon_pipeline::learning::gnn::math::cosine_similarity;
use archon_pipeline::learning::gnn::{
    GnnConfig, GnnEnhancer, TrajectoryEdge, TrajectoryGraph, TrajectoryNode,
};
use serde::Deserialize;
use std::collections::HashMap;

// ---------------------------------------------------------------------------
// Fixture JSON shape
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
struct FixtureFile {
    seed: u64,
    config: FixtureConfig,
    layer_ids: Vec<String>,
    layer_weights: HashMap<String, FixtureLayerWeights>,
    fixtures: Vec<Fixture>,
}

#[derive(Debug, Deserialize)]
struct FixtureConfig {
    #[serde(rename = "inputDim")]
    input_dim: usize,
    #[serde(rename = "outputDim")]
    output_dim: usize,
}

#[derive(Debug, Deserialize)]
struct FixtureLayerWeights {
    #[serde(rename = "inDim")]
    in_dim: usize,
    #[serde(rename = "outDim")]
    out_dim: usize,
    seed: u64,
    first_row_sample: Vec<f32>,
    #[serde(default)]
    weights: Vec<Vec<f32>>,
}

#[derive(Debug, Deserialize)]
struct Fixture {
    name: String,
    seed: u64,
    #[serde(default)]
    input: Option<Vec<Option<f32>>>,
    #[serde(default)]
    center: Option<Vec<Option<f32>>>,
    graph: Option<FixtureGraph>,
    #[serde(default)]
    expected: Vec<Option<f32>>,
}

#[derive(Debug, Deserialize)]
struct FixtureGraph {
    nodes: Vec<FixtureNode>,
    edges: Vec<FixtureEdge>,
}

#[derive(Debug, Deserialize)]
struct FixtureNode {
    id: String,
    embedding: Vec<f32>,
}

#[derive(Debug, Deserialize)]
struct FixtureEdge {
    source: String,
    target: String,
    weight: f32,
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn load_fixtures() -> FixtureFile {
    let json_str = include_str!("fixtures/gnn_expected.json");
    serde_json::from_str(json_str).expect("Failed to parse gnn_expected.json")
}

fn to_f32_vec(v: &[Option<f32>]) -> Vec<f32> {
    v.iter().map(|o| o.unwrap_or(f32::NAN)).collect()
}

fn build_enhancer(fixtures: &FixtureFile) -> GnnEnhancer {
    GnnEnhancer::with_in_memory_weights(GnnConfig::default(), CacheConfig::default(), fixtures.seed)
}

// ---------------------------------------------------------------------------
// Pre-check: initialized weights match
// ---------------------------------------------------------------------------

#[test]
fn weight_initialization_matches_ts() {
    let fixtures = load_fixtures();
    let enhancer = build_enhancer(&fixtures);

    for layer_id in &fixtures.layer_ids {
        let ts_weights = &fixtures.layer_weights[layer_id];
        let rust_weights = enhancer.weight_store().get_weights(layer_id);

        assert_eq!(
            rust_weights.len(),
            ts_weights.out_dim,
            "Layer {}: Rust has {} rows, TS has {}",
            layer_id,
            rust_weights.len(),
            ts_weights.out_dim
        );

        // Check first row sample
        if let Some(first_row) = rust_weights.first() {
            for (i, &ts_val) in ts_weights.first_row_sample.iter().enumerate() {
                let rust_val = first_row[i];
                let diff = (rust_val - ts_val).abs();
                assert!(
                    diff < f32::EPSILON * 10.0,
                    "Layer {}: weight[0][{}] mismatch — Rust={:.12}, TS={:.12}, diff={:.12}",
                    layer_id,
                    i,
                    rust_val,
                    ts_val,
                    diff
                );
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Forward pass parity (non-graph fixtures)
// ---------------------------------------------------------------------------

#[test]
fn forward_pass_parity_all_input_fixtures() {
    let fixtures = load_fixtures();
    let enhancer = build_enhancer(&fixtures);

    let input_fixtures: Vec<&Fixture> = fixtures
        .fixtures
        .iter()
        .filter(|f| f.input.is_some())
        .collect();

    assert!(
        !input_fixtures.is_empty(),
        "No input fixtures found in gnn_expected.json"
    );

    let mut failures = Vec::new();

    for fixture in &input_fixtures {
        enhancer.clear_cache();
        let input_opt = fixture.input.as_ref().unwrap();
        let input = to_f32_vec(input_opt);

        if fixture.name == "nan_input" {
            // NaN input should produce zero-padded fallback
            let result = enhancer.enhance(&input, None, None, false);
            assert!(
                !result
                    .enhanced
                    .iter()
                    .any(|v| v.is_nan() || v.is_infinite()),
                "NaN input fixture '{}' should produce fallback with no NaN/Inf",
                fixture.name
            );
            continue;
        }

        let result = enhancer.enhance(&input, None, None, false);
        let expected = to_f32_vec(&fixture.expected);

        // Zero-magnitude vectors: cosine similarity is undefined. If both are
        // (near-)zero, they match by construction since the forward pass is
        // deterministic for zero inputs.
        let res_mag: f32 = result.enhanced.iter().map(|v| v * v).sum();
        let exp_mag: f32 = expected.iter().map(|v| v * v).sum();
        if res_mag < 1e-12 && exp_mag < 1e-12 {
            continue;
        }

        let cos_sim = cosine_similarity(&result.enhanced, &expected);

        if cos_sim < 0.999 {
            // Compute first 10 diverging indices for diagnostics
            let mut diverged = Vec::new();
            let min_len = result.enhanced.len().min(expected.len());
            for i in 0..min_len {
                let diff = (result.enhanced[i] - expected[i]).abs();
                if diff > 1e-4 {
                    diverged.push((i, result.enhanced[i], expected[i], diff));
                    if diverged.len() >= 10 {
                        break;
                    }
                }
            }
            failures.push((fixture.name.clone(), cos_sim, diverged));
        }
    }

    if !failures.is_empty() {
        for (name, cos, diverged) in &failures {
            eprintln!("FAIL {}: cosine_sim = {:.6} (threshold: 0.999)", name, cos);
            for (i, rust_val, ts_val, diff) in diverged {
                eprintln!(
                    "  [{}] Rust={:.8} TS={:.8} diff={:.8}",
                    i, rust_val, ts_val, diff
                );
            }
        }
        panic!(
            "{} of {} input fixtures below cosine threshold 0.999",
            failures.len(),
            input_fixtures.len()
        );
    }
}

// ---------------------------------------------------------------------------
// Graph fixture parity
// ---------------------------------------------------------------------------

#[test]
fn graph_forward_pass_parity() {
    let fixtures = load_fixtures();
    let enhancer = build_enhancer(&fixtures);

    let graph_fixtures: Vec<&Fixture> = fixtures
        .fixtures
        .iter()
        .filter(|f| f.graph.is_some())
        .collect();

    for fixture in &graph_fixtures {
        enhancer.clear_cache();
        let graph_data = fixture.graph.as_ref().unwrap();
        let center_opt = fixture.center.as_ref().unwrap();
        let center = to_f32_vec(center_opt);

        let graph = TrajectoryGraph {
            nodes: graph_data
                .nodes
                .iter()
                .map(|n| TrajectoryNode {
                    id: n.id.clone(),
                    embedding: n.embedding.clone(),
                })
                .collect(),
            edges: graph_data
                .edges
                .iter()
                .map(|e| TrajectoryEdge {
                    source: e.source.clone(),
                    target: e.target.clone(),
                    weight: e.weight,
                })
                .collect(),
        };

        let result = enhancer.enhance_with_graph(&center, &graph);
        let expected = to_f32_vec(&fixture.expected);
        let cos_sim = cosine_similarity(&result.enhanced, &expected);

        assert!(
            cos_sim >= 0.999,
            "Graph fixture '{}': cosine_sim = {:.6} < 0.999",
            fixture.name,
            cos_sim
        );
    }
}

// ---------------------------------------------------------------------------
// Determinism: same seed = same output
// ---------------------------------------------------------------------------

#[test]
fn same_seed_produces_same_output() {
    let e1 = GnnEnhancer::with_in_memory_weights(GnnConfig::default(), CacheConfig::default(), 42);
    let e2 = GnnEnhancer::with_in_memory_weights(GnnConfig::default(), CacheConfig::default(), 42);

    let input = vec![0.5; 1536];
    let r1 = e1.enhance(&input, None, None, false);
    let r2 = e2.enhance(&input, None, None, false);

    assert_eq!(
        r1.enhanced, r2.enhanced,
        "Same seed should produce identical output"
    );
}
